name: Популярные игровые слоты
description: >
    Все об игровых слотах. Здень вы найдете популярные и надержные игровые слоты в онлайн казино
master_repo: false
url: "http://jarvisblog.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Игровые слоты
  # Social networking links used in footer. Update and remove as you like.
  github: https://github.com/jarvisblog
ыфв